# Generated by Django 4.0.4 on 2022-05-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_doctor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.doctor'),
            preserve_default=False,
        ),
    ]
